title: "Fortgeschrittene Programmierkonzepte (FPK)"
email: marcel.tilly@th-rosenheim.de
description: "Materialien zum Pflichtmodul Fortgeschrittene Programmierkonzepte"
baseurl: ""
url: "https://hsro-inf-fpk.github.io"
exclude: ["LICENSE", "Remarks.md", "examples"]
github_username: ["matowrx"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
